FROM caddy:2.10.0-alpine

ARG ALPINE_MIRROR=""

RUN if [ -n "$ALPINE_MIRROR" ]; then \
      sed -i "s|https://dl-cdn.alpinelinux.org/alpine|${ALPINE_MIRROR%/}|g" /etc/apk/repositories; \
    fi
RUN apk add --no-cache nss-tools bash curl

COPY Caddyfile.ce /etc/caddy/Caddyfile
