# Generated by AgentPM on 2026-07-13

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_work_item_kind_labels(apps, schema_editor):
    Project = apps.get_model("db", "Project")
    Label = apps.get_model("db", "Label")
    colors = {"requirement": "#4F46E5", "bug": "#DC2626", "task": "#0F766E", "analysis": "#B45309"}
    for project in Project.objects.all().iterator():
        for kind, color in colors.items():
            Label.objects.get_or_create(
                workspace_id=project.workspace_id,
                project_id=project.id,
                name=f"kind:{kind}",
                defaults={"color": color, "description": f"AgentPM work item kind: {kind}"},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRegistrationApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("agent_id", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("requested_role", models.CharField(default="member", max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=16)),
                ("source", models.CharField(default="bootstrap", max_length=32)),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("reviewed_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_agent_applications", to="db.user")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={"db_table": "agent_registration_applications", "ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="agentregistrationapplication",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True), ("status", "pending")), fields=("workspace", "agent_id"), name="unique_pending_agent_application"),
        ),
        migrations.RunPython(seed_work_item_kind_labels, migrations.RunPython.noop),
    ]
