# Generated by Mesh. Safe to run repeatedly.

from django.db import migrations


DEFAULT_ROLES = (
    ("pm", "PM", ["work.read", "work.assign", "loop.draft", "handoff.select"]),
    ("developer", "Developer", ["work.read", "work.update", "code.write", "test.run"]),
    ("tester", "Tester", ["work.read", "work.comment", "test.run", "handoff.reject"]),
    ("reviewer", "Reviewer", ["work.read", "work.comment", "review.approve"]),
    ("observer", "Observer", ["work.read", "work.comment"]),
)


def _agent_id(user):
    local_part = (user.email or "").split("@", 1)[0].lower()
    username = (user.username or "").lower()
    candidate = local_part or username or f"bot-{str(user.id)[:8]}"
    return candidate.removeprefix("agent-")[:64]


def seed_mesh_identity_and_roles(apps, schema_editor):
    AgentProfile = apps.get_model("db", "AgentProfile")
    MeshFunctionalRole = apps.get_model("db", "MeshFunctionalRole")
    Project = apps.get_model("db", "Project")
    User = apps.get_model("db", "User")
    WorkspaceMember = apps.get_model("db", "WorkspaceMember")

    for project in Project.objects.filter(deleted_at__isnull=True).iterator():
        for index, (key, name, capabilities) in enumerate(DEFAULT_ROLES):
            MeshFunctionalRole.objects.get_or_create(
                workspace_id=project.workspace_id,
                project_id=project.id,
                key=key,
                deleted_at__isnull=True,
                defaults={
                    "name": name,
                    "capabilities": capabilities,
                    "is_default": True,
                    "sort_order": index * 1000,
                },
            )

    bot_ids = User.objects.filter(is_bot=True).values_list("id", flat=True)
    memberships = WorkspaceMember.objects.filter(
        member_id__in=bot_ids,
        is_active=True,
        deleted_at__isnull=True,
    ).select_related("member")
    for membership in memberships.iterator():
        user = membership.member
        agent_id = _agent_id(user)
        conflict = AgentProfile.objects.filter(
            workspace_id=membership.workspace_id,
            agent_id=agent_id,
            deleted_at__isnull=True,
        ).exclude(user_id=user.id)
        if conflict.exists():
            agent_id = f"{agent_id[:55]}-{str(user.id)[:8]}"
        AgentProfile.objects.get_or_create(
            workspace_id=membership.workspace_id,
            user_id=user.id,
            deleted_at__isnull=True,
            defaults={
                "agent_id": agent_id,
                "agent_type": "autonomous",
                "runtime_provider": "legacy",
                "status": "active",
                "trust_level": "verified",
            },
        )


class Migration(migrations.Migration):
    dependencies = [("db", "0123_agentexecutionprofile_agentprofile_and_more")]

    operations = [migrations.RunPython(seed_mesh_identity_and_roles, migrations.RunPython.noop)]
